# Generated by Django 5.2.6 on 2025-09-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_url', models.FileField(upload_to='files/')),
                ('file_desc', models.TextField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('upvote_count', models.IntegerField(default=0)),
                ('downvote_count', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
