# Generated by Django 6.0 on 2025-12-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=50)),
                ('program_desc', models.TextField()),
                ('courses', models.ManyToManyField(related_name='programs', to='curriculum.course')),
            ],
        ),
    ]
