# Generated by Django 5.2.6 on 2025-09-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('testimonial_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('isVisible', models.BooleanField(default=True)),
            ],
        ),
    ]
