# Generated by Django 5.2.6 on 2025-09-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='isVisible',
            new_name='is_visible',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
