# Generated by Django 5.2.6 on 2025-09-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_rename_isvisible_testimonial_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
