# Generated by Django 5.2.6 on 2025-09-27 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('testimonial', '0003_alter_testimonial_testimonial_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.course'),
        ),
    ]
