# Generated by Django 5.2.6 on 2025-10-18 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('forumId', models.AutoField(primary_key=True, serialize=False)),
                ('forumTitle', models.TextField()),
                ('forumDesc', models.TextField()),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.course')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('threadId', models.AutoField(primary_key=True, serialize=False)),
                ('threadTitle', models.TextField()),
                ('dateCreated', models.DateTimeField()),
                ('upvoteCount', models.IntegerField(default=0)),
                ('downvoteCount', models.IntegerField(default=0)),
                ('isVisible', models.BooleanField(default=True)),
                ('forumId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.forum')),
                ('studentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.student')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('upvoteCount', models.IntegerField(default=0)),
                ('downvoteCount', models.IntegerField(default=0)),
                ('isVisible', models.BooleanField(default=True)),
                ('studentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.student')),
                ('threadId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.thread')),
            ],
        ),
    ]
