# Generated by Django 5.2.6 on 2025-09-27 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('forumId', models.AutoField(primary_key=True, serialize=False)),
                ('forumTitle', models.TextField()),
                ('forumDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('threadId', models.AutoField(primary_key=True, serialize=False)),
                ('threadTitle', models.TextField()),
                ('dateCreated', models.DateTimeField()),
                ('upvoteCount', models.IntegerField(default=0)),
                ('downvoteCount', models.IntegerField(default=0)),
                ('isVisible', models.BooleanField(default=True)),
                ('forumId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.forum')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('upvoteCount', models.IntegerField(default=0)),
                ('downvoteCount', models.IntegerField(default=0)),
                ('isVisible', models.BooleanField(default=True)),
                ('threadId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.thread')),
            ],
        ),
    ]
