# Generated by Django 5.2.6 on 2025-12-17 09:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.comment'),
        ),
        migrations.CreateModel(
            name='CommentSnapshot',
            fields=[
                ('snapshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('snapshot_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.comment')),
            ],
        ),
    ]
