# Generated by Django 5.2.6 on 2025-09-27 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingID', models.AutoField(primary_key=True, serialize=False)),
                ('isUpvoted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommentRating',
            fields=[
                ('rating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rating.rating')),
            ],
            bases=('rating.rating',),
        ),
        migrations.CreateModel(
            name='FileRating',
            fields=[
                ('rating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rating.rating')),
            ],
            bases=('rating.rating',),
        ),
        migrations.CreateModel(
            name='ThreadRating',
            fields=[
                ('rating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rating.rating')),
            ],
            bases=('rating.rating',),
        ),
    ]
