# Generated by Django 5.2.6 on 2025-09-30 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discussion', '0001_initial'),
        ('file', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingId', models.AutoField(primary_key=True, serialize=False)),
                ('isUpvoted', models.BooleanField(default=False)),
                ('studentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
        ),
        migrations.CreateModel(
            name='CommentRating',
            fields=[
                ('rating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rating.rating')),
                ('commentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.comment')),
            ],
            bases=('rating.rating',),
        ),
        migrations.CreateModel(
            name='FileRating',
            fields=[
                ('rating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rating.rating')),
                ('fileId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file.file')),
            ],
            bases=('rating.rating',),
        ),
        migrations.CreateModel(
            name='ThreadRating',
            fields=[
                ('rating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rating.rating')),
                ('threadId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.thread')),
            ],
            bases=('rating.rating',),
        ),
    ]
