# Generated by Django 5.2.6 on 2025-12-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discussion', '0001_initial'),
        ('file', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentRating',
            fields=[
                ('ratingId', models.AutoField(primary_key=True, serialize=False)),
                ('isUpvoted', models.BooleanField(default=False)),
                ('commentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.comment')),
                ('studentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileRating',
            fields=[
                ('ratingId', models.AutoField(primary_key=True, serialize=False)),
                ('isUpvoted', models.BooleanField(default=False)),
                ('fileId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('studentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThreadRating',
            fields=[
                ('ratingId', models.AutoField(primary_key=True, serialize=False)),
                ('isUpvoted', models.BooleanField(default=False)),
                ('studentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.student')),
                ('threadId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.thread')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
