# Generated by Django 5.2.6 on 2025-09-30 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
        ('file', '0001_initial'),
        ('rating', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='ratingID',
            new_name='ratingId',
        ),
        migrations.AddField(
            model_name='commentrating',
            name='commentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.comment'),
        ),
        migrations.AddField(
            model_name='filerating',
            name='fileId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file.file'),
        ),
        migrations.AddField(
            model_name='rating',
            name='studentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.student'),
        ),
        migrations.AddField(
            model_name='threadrating',
            name='threadId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.thread'),
        ),
    ]
